local gfxTables = require("gfxTables")
local coolTable = gfxTables.newTable()
coolTable:setShowEnumerator(true)
coolTable:setDefaultEntryValue("empty")
coolTable:setSeparateEntries(true)
coolTable:setPadding(2)
coolTable:insertColumns("First Name", "Last Name", "Email")
coolTable:insertEntry({"Alejandro", "Alzate", "alejandro-alzate@github.com"})
print(coolTable)